import pandas as pd 
import numpy as np 
from sklearn.preprocessing import StandardScaler, MinMaxScaler, LabelEncoder
from sklearn.model_selection import train_test_split
import json


# Loading the original dataframe
df = pd.read_csv('Dataset/Original_Dataset.csv', index_col = 'Unnamed: 0')
print(df.info())

# Converting all '-' values to NaNs
df = df.replace('-', np.nan, inplace = True)

# Converting all possible columns to floats (except for the equipment, test_results and new_results columns)
for col in df.columns:
    if col not in ['Eqwuipment', 'Test_Results', 'New_Results']:
        try:
            df[col] = df[col].astype(float)
        except:
            pass

# Replacing all NaN values from the columns by a value according to the columns' means and std
for col in df.columns:
    if df[col].dtype == 'float64':
        df[col].fillna(df[col].mean() + df[col].std(), inplace = True)

# Removing the equipment and test_results columns, and generating the X and y structures
X = df.drop(columns = ['Equipment', 'Test_Results', 'New_Results'], axis = 1)
y = df['New_Results']

# Using label encoder to convert the y labels into integer values
y_classes = LabelEncoder()
y = y_classes.fit_transform(y)
# Just saving the classes to store in a json file
y_mapping = dict(zip(y_classes.classes_, y_classes.transform(y_classes.classes_)))
json_object = json.dumps(y_mapping, indent = 4)
with open('Processed_Files/y_classes.json', 'w') as file:
    file.write(json_object)

# Generating some scaled datasets and storing those
# NOTE: MinMaxScaler works best for autoencoders, while other methods such as PCA require centred data, such as the one generated by StandardScaler
standard_scaler_data = StandardScaler().fit_transform(X)
min_max_scaler_data = MinMaxScaler().fit_transform(X)

# Storing multiple pre-processed files to then be used by the models
np.savetxt('Processed_Files/X_StandardScaler.csv', standard_scaler_data, delimiter = ',')
np.savetxt('Processed_Files/X_MinMaxScaler.csv', min_max_scaler_data, delimiter = ',')
np.savetxt('Processed_Files/X_Original.csv', X, delimiter = ',')
np.savetxt('Processed_Files/y_LabelEncoder.csv', y, delimiter = ',')
np.savetxt('Processed_Files/y_Original', y, delimiter = ',')
