# Main settings to train each model
models:
  num_trials: 250
  train_split: 0.9
  validation_split: 0.1
  # Epochs only applicable to Deep Learning models
  num_epochs_trials: 5
  num_final_epochs: 20
  available_models: [PCA, ICA, SVD, RF, AE, NMF, RFE, LDA]
  # available_models: [PCA, ICA, SVD, LDA, RF, AE, VAE]
  DL_models: [AE, VAE]
  FS_models: [RFE, RF]

# A series of useful directories for each script
directories:
  best_model: './Models/Models' # Path where each of the best models is saved
  datasets: './Data'
  parameters: './Models/Parameters'
  search_space: './Models/SearchSpace'
  results: './Results'
