# Main settings to train each model
models:
  num_trials: 10
  train_split: 0.8
  validation_split: 0.1
  # Epochs only applicable to Deep Learning models
  num_epochs_trials: 5
  num_final_epochs: 20
  available_models: [PCA, ICA, AE, VAE, SVD, LDA, RF]
  DL_models: [AE, VAE]

# A series of useful directories for each script
directories:
  best_model: 'C:/Users/Lenovo\OneDrive - Universidade de Aveiro/Doutoramento/ILLIANCE_Project/DR_Comparison/DR_Comparison/Models' # Path where each of the best models is saved
  datasets: 'C:/Users/Lenovo\OneDrive - Universidade de Aveiro/Doutoramento/ILLIANCE_Project/DR_Comparison/DR_Comparison/Processed_Files'
