models:
  num_trials: 500
  train_split: 0.8
  validation_split: 0.9
  # Epochs only applicable to Deep Learning models
  num_epochs_trials: 10
  num_final_epochs: 500

directories:
  best_model: "C:/Users/Lenovo\OneDrive - Universidade de Aveiro/Doutoramento/ILLIANCE_Project/DR_Comparison/DR_Comparison/Models" # Path where each of the best models is saved
  datasets: "C:/Users/Lenovo\OneDrive - Universidade de Aveiro/Doutoramento/ILLIANCE_Project/DR_Comparison/DR_Comparison/Processed_Files"
  