# Main settings to train each model
models:
  num_trials: 250
  train_split: 0.9
  validation_split: 0.1
  # Epochs only applicable to Deep Learning models
  num_epochs_trials: 5
  num_final_epochs: 20
  available_models: [PCA, ICA, SVD, RF, AE, NMF, RFE]
  DL_models: [AE]
  FS_models: [RFE, RF]

# A series of useful directories for each script
directories:
  best_model: './Models/Models' # Path where each of the best models is saved
  datasets: './Data'
  parameters: './Models/Parameters'
  search_space: './Models/SearchSpace'
  results: './Results'
  default_tests: './Results/Default_Tests'
  time_tests: './Results/Times'
  dr_time_tests: './Results/Times/DR'
  opt_results: './Models/Opt_Results'
